-- Create "users" table
CREATE TABLE "public"."users" (
  "id" uuid NOT NULL,
  "email" character varying NOT NULL,
  "name" character varying NULL,
  "handle" character varying NOT NULL,
  "stripe_customer_id" character varying NULL,
  "stripe_sub_id" character varying NULL,
  "plan" character varying NOT NULL DEFAULT 'free',
  "credits" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create index "users_handle_key" to table: "users"
CREATE UNIQUE INDEX "users_handle_key" ON "public"."users" ("handle");
-- Create "themes" table
CREATE TABLE "public"."themes" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "slug" character varying NOT NULL,
  "prompt" character varying NOT NULL,
  "css_tokens" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "user_themes" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "themes_users_themes" FOREIGN KEY ("user_themes") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "themes_slug_key" to table: "themes"
CREATE UNIQUE INDEX "themes_slug_key" ON "public"."themes" ("slug");
-- Create "albums" table
CREATE TABLE "public"."albums" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "slug" character varying NOT NULL,
  "description" character varying NULL,
  "visibility" character varying NOT NULL DEFAULT 'unlisted',
  "original_image_visibility" character varying NOT NULL DEFAULT 'hide',
  "password_hash" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "album_default_theme" uuid NULL,
  "user_albums" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "albums_themes_default_theme" FOREIGN KEY ("album_default_theme") REFERENCES "public"."themes" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "albums_users_albums" FOREIGN KEY ("user_albums") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "albums_slug_key" to table: "albums"
CREATE UNIQUE INDEX "albums_slug_key" ON "public"."albums" ("slug");
-- Create "album_users" table
CREATE TABLE "public"."album_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'viewer',
  "created_at" timestamptz NOT NULL,
  "album_members" uuid NOT NULL,
  "user_memberships" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "album_users_albums_members" FOREIGN KEY ("album_members") REFERENCES "public"."albums" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "album_users_users_memberships" FOREIGN KEY ("user_memberships") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "files" table
CREATE TABLE "public"."files" (
  "id" uuid NOT NULL,
  "provider" character varying NOT NULL DEFAULT 'cloudflare_images',
  "cloudflare_id" character varying NOT NULL,
  "original_name" character varying NOT NULL,
  "mime" character varying NOT NULL,
  "size_bytes" bigint NOT NULL,
  "width" bigint NULL,
  "height" bigint NULL,
  "checksum_sha256" character varying NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "original_photos" table
CREATE TABLE "public"."original_photos" (
  "id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL,
  "album_original_photos" uuid NOT NULL,
  "file_original_of" uuid NOT NULL,
  "user_uploaded_photos" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "original_photos_albums_original_photos" FOREIGN KEY ("album_original_photos") REFERENCES "public"."albums" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "original_photos_files_original_of" FOREIGN KEY ("file_original_of") REFERENCES "public"."files" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "original_photos_users_uploaded_photos" FOREIGN KEY ("user_uploaded_photos") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "generated_photos" table
CREATE TABLE "public"."generated_photos" (
  "id" uuid NOT NULL,
  "state" character varying NOT NULL DEFAULT 'processing',
  "error_msg" character varying NULL,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz NULL,
  "retries" bigint NOT NULL DEFAULT 0,
  "file_generated_of" uuid NULL,
  "original_photo_generated" uuid NOT NULL,
  "theme_generated" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "generated_photos_files_generated_of" FOREIGN KEY ("file_generated_of") REFERENCES "public"."files" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "generated_photos_original_photos_generated" FOREIGN KEY ("original_photo_generated") REFERENCES "public"."original_photos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "generated_photos_themes_generated" FOREIGN KEY ("theme_generated") REFERENCES "public"."themes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
