-- Create "users" table
CREATE TABLE "public"."users" (
  "id" character varying NOT NULL,
  "email" character varying NOT NULL,
  "name" character varying NULL,
  "stripe_customer_id" character varying NULL,
  "stripe_sub_id" character varying NULL,
  "plan" character varying NOT NULL DEFAULT 'free',
  "credits" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create "themes" table
CREATE TABLE "public"."themes" (
  "id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "slug" character varying NOT NULL,
  "prompt" character varying NOT NULL,
  "css_tokens" jsonb NULL,
  "created_at" timestamptz NOT NULL,
  "user_themes" character varying NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "themes_users_themes" FOREIGN KEY ("user_themes") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- Create index "themes_slug_key" to table: "themes"
CREATE UNIQUE INDEX "themes_slug_key" ON "public"."themes" ("slug");
-- Create "albums" table
CREATE TABLE "public"."albums" (
  "id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "slug" character varying NOT NULL,
  "description" character varying NULL,
  "visibility" character varying NOT NULL DEFAULT 'unlisted',
  "original_image_visibility" character varying NOT NULL DEFAULT 'hide',
  "password_hash" character varying NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "album_default_theme" character varying NULL,
  "user_albums" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "albums_themes_default_theme" FOREIGN KEY ("album_default_theme") REFERENCES "public"."themes" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "albums_users_albums" FOREIGN KEY ("user_albums") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "albums_slug_key" to table: "albums"
CREATE UNIQUE INDEX "albums_slug_key" ON "public"."albums" ("slug");
-- Create "album_invite_links" table
CREATE TABLE "public"."album_invite_links" (
  "id" character varying NOT NULL,
  "token" character varying NOT NULL,
  "role" character varying NOT NULL DEFAULT 'viewer',
  "max_uses" bigint NULL,
  "uses" bigint NOT NULL DEFAULT 0,
  "expires_at" timestamptz NULL,
  "revoked_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "album_invite_links" character varying NOT NULL,
  "user_created_invite_links" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "album_invite_links_albums_invite_links" FOREIGN KEY ("album_invite_links") REFERENCES "public"."albums" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "album_invite_links_users_created_invite_links" FOREIGN KEY ("user_created_invite_links") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "album_invite_links_token_key" to table: "album_invite_links"
CREATE UNIQUE INDEX "album_invite_links_token_key" ON "public"."album_invite_links" ("token");
-- Create "album_invites" table
CREATE TABLE "public"."album_invites" (
  "id" character varying NOT NULL,
  "email" character varying NOT NULL,
  "role" character varying NOT NULL DEFAULT 'viewer',
  "status" character varying NOT NULL DEFAULT 'pending',
  "token" character varying NOT NULL,
  "expires_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "revoked_at" timestamptz NULL,
  "accepted_at" timestamptz NULL,
  "album_email_invites" character varying NOT NULL,
  "album_invite_accepted_by" character varying NULL,
  "user_created_email_invites" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "album_invites_albums_email_invites" FOREIGN KEY ("album_email_invites") REFERENCES "public"."albums" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "album_invites_users_accepted_by" FOREIGN KEY ("album_invite_accepted_by") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "album_invites_users_created_email_invites" FOREIGN KEY ("user_created_email_invites") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "album_invites_token_key" to table: "album_invites"
CREATE UNIQUE INDEX "album_invites_token_key" ON "public"."album_invites" ("token");
-- Create "album_users" table
CREATE TABLE "public"."album_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role" character varying NOT NULL DEFAULT 'viewer',
  "created_at" timestamptz NOT NULL,
  "album_members" character varying NOT NULL,
  "user_memberships" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "album_users_albums_members" FOREIGN KEY ("album_members") REFERENCES "public"."albums" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "album_users_users_memberships" FOREIGN KEY ("user_memberships") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "files" table
CREATE TABLE "public"."files" (
  "id" character varying NOT NULL,
  "provider" character varying NOT NULL DEFAULT 'cloudflare_images',
  "cloudflare_id" character varying NOT NULL,
  "original_name" character varying NOT NULL,
  "mime" character varying NOT NULL,
  "size_bytes" bigint NOT NULL,
  "width" bigint NULL,
  "height" bigint NULL,
  "checksum_sha256" character varying NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create "original_photos" table
CREATE TABLE "public"."original_photos" (
  "id" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "album_original_photos" character varying NOT NULL,
  "file_original_of" character varying NOT NULL,
  "user_uploaded_photos" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "original_photos_albums_original_photos" FOREIGN KEY ("album_original_photos") REFERENCES "public"."albums" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "original_photos_files_original_of" FOREIGN KEY ("file_original_of") REFERENCES "public"."files" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "original_photos_users_uploaded_photos" FOREIGN KEY ("user_uploaded_photos") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "generated_photos" table
CREATE TABLE "public"."generated_photos" (
  "id" character varying NOT NULL,
  "state" character varying NOT NULL DEFAULT 'processing',
  "error_msg" character varying NULL,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz NULL,
  "retries" bigint NOT NULL DEFAULT 0,
  "file_generated_of" character varying NULL,
  "original_photo_generated" character varying NOT NULL,
  "theme_generated" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "generated_photos_files_generated_of" FOREIGN KEY ("file_generated_of") REFERENCES "public"."files" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "generated_photos_original_photos_generated" FOREIGN KEY ("original_photo_generated") REFERENCES "public"."original_photos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "generated_photos_themes_generated" FOREIGN KEY ("theme_generated") REFERENCES "public"."themes" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "credit_usages" table
CREATE TABLE "public"."credit_usages" (
  "id" character varying NOT NULL,
  "amount" bigint NOT NULL DEFAULT 1,
  "reason" character varying NOT NULL DEFAULT 'generate',
  "created_at" timestamptz NOT NULL,
  "generated_photo_credit_usages" character varying NULL,
  "original_photo_credit_usages" character varying NULL,
  "theme_credit_usages" character varying NULL,
  "user_credit_usages" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "credit_usages_generated_photos_credit_usages" FOREIGN KEY ("generated_photo_credit_usages") REFERENCES "public"."generated_photos" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "credit_usages_original_photos_credit_usages" FOREIGN KEY ("original_photo_credit_usages") REFERENCES "public"."original_photos" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "credit_usages_themes_credit_usages" FOREIGN KEY ("theme_credit_usages") REFERENCES "public"."themes" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "credit_usages_users_credit_usages" FOREIGN KEY ("user_credit_usages") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "prices" table
CREATE TABLE "public"."prices" (
  "id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "stripe_price_id" character varying NOT NULL,
  "credits" bigint NOT NULL DEFAULT 1,
  "active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "prices_stripe_price_id_key" to table: "prices"
CREATE UNIQUE INDEX "prices_stripe_price_id_key" ON "public"."prices" ("stripe_price_id");
-- Create "purchases" table
CREATE TABLE "public"."purchases" (
  "id" character varying NOT NULL,
  "stripe_checkout_session_id" character varying NOT NULL,
  "stripe_payment_intent_id" character varying NULL,
  "stripe_customer_id" character varying NULL,
  "amount_total" bigint NULL,
  "currency" character varying NULL,
  "credits_granted" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "price_purchases" character varying NULL,
  "user_purchases" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "purchases_prices_purchases" FOREIGN KEY ("price_purchases") REFERENCES "public"."prices" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "purchases_users_purchases" FOREIGN KEY ("user_purchases") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
